import {
  CalendarMinus,
  CurrencyDollar,
  User,
  Bulb,
  ChartPie,
  Home,
  Send,
  Mail,
  Pin,
  Building,
  Phone,
  Messages,
  ListCheck,
  Meat,
  Virus,
  Photo,
  ArrowNarrowRight,
  ChevronsRight,
  ChevronRight,
  MapPin,
  Artboard,
  Code,
  Tool,
  ClipboardList,
  Rocket,
  Box,
  Circles,
  CircleSquare,
  Diamond,
  Stack,
  Triangle,
  Checks,
  ShieldCheck,
  Flame,
  TrendingUp,
  Users,
  Puzzle,
  BrandHtml5,
  BrandTailwind,
} from "tabler-icons-react";

const iconOptions = {
  calendar: CalendarMinus,
  dollar: CurrencyDollar,
  user: User,
  bulb: Bulb,
  ratio: ChartPie,
  home: Home,
  send: Send,
  mail: Mail,
  pin: Pin,
  building: Building,
  phone: Phone,
  messages: Messages,
  listCheck: ListCheck,
  meat: Meat,
  virus: Virus,
  photo: Photo,
  arrowNarrowRight: ArrowNarrowRight,
  chevronsRight: ChevronsRight,
  chevronRight: ChevronRight,
  mapPin: MapPin,
  artboard: Artboard,
  code: Code,
  tool: Tool,
  clipboardList: ClipboardList,
  rocket: Rocket,
  box: Box,
  circles: Circles,
  circleSquare: CircleSquare,
  diamond: Diamond,
  stack: Stack,
  triangle: Triangle,
  checks: Checks,
  shieldCheck: ShieldCheck,
  flame: Flame,
  trendingUp: TrendingUp,
  users: Users,
  puzzle: Puzzle,
  html: BrandHtml5,
  tailwind: BrandTailwind,
};

export const Icon = ({ name, className = "" }) => {
  const iconName = name || Object.keys(iconOptions)[0];
  const IconSVG = iconOptions[iconName];

  return <IconSVG className={`${className}`} strokeWidth={1.5} />;
};
